apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl
  namespace: sensor-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl
  template:
    metadata:
      labels:
        app: etl
    spec:
      containers:
        - name: etl
          image: sensor-platform-etl:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KAFKA_CDC_TOPIC
              value: "sensor_cdc.public.sensor_raw"
            - name: KAFKA_CONSUMER_GROUP
              value: "etl-inference"
            - name: INFERENCE_URL
              value: "http://inference:8000"
            - name: OTEL_SERVICE_NAME
              value: etl
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: etl
  namespace: sensor-platform
spec:
  selector:
    app: etl
  ports: []
  type: ClusterIP
  clusterIP: None
